{
 "title": "Tansu Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Object Store Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tansu_object_store_request_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Object Store Request Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(tansu_object_store_request_error_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Store Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_object_store_request_duration_milliseconds_bucket{method=\"put_opts\"}[$__rate_interval])))",
     "legendFormat": "put_opts"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_object_store_request_duration_milliseconds_bucket{method=\"get_opts\"}[$__rate_interval])))",
     "legendFormat": "get_opts"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_object_store_request_duration_milliseconds_bucket{method=\"list_with_delimiter\"}[$__rate_interval])))",
     "legendFormat": "list_with_delimiter"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(tansu_api_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minio cluster raw free bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "minio_cluster_capacity_raw_free_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_response_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minio usage total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "minio_cluster_usage_total_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_request_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tansu_request_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}